### ISSUE TITLE
Worker repeatedly times out and is unable to recover

### ISSUE THREAD

**Issue by oberones** [geminabox/geminabox#248]
After updating from geminabox 0.13.1 to 0.13.3, our geminabox server stopped serving proxy requests for gem installs. The following set of messages is repeating endlessly (different PIDs obviously):

```
2016-10-18_20:09:53.56204 172.26.10.155 - - [18/Oct/2016:20:09:53 +0000] "GET /latest_specs.4.8.gz HTTP/1.1" 200 1045028 7.8978
2016-10-18_20:10:54.25059 E, [2016-10-18T20:10:54.240912 #895] ERROR -- : worker=0 PID:12988 timeout (61s > 60s), killing
2016-10-18_20:10:54.25305 E, [2016-10-18T20:10:54.252929 #895] ERROR -- : reaped #<Process::Status: pid 12988 SIGKILL (signal 9)> worker=0
2016-10-18_20:10:54.25343 I, [2016-10-18T20:10:54.253344 #895]  INFO -- : worker=0 spawning...
2016-10-18_20:10:54.25517 I, [2016-10-18T20:10:54.254792 #13457]  INFO -- : worker=0 spawned pid=13457
2016-10-18_20:10:54.25554 I, [2016-10-18T20:10:54.255369 #13457]  INFO -- : Refreshing Gem list
2016-10-18_20:10:54.73047 I, [2016-10-18T20:10:54.730305 #13457]  INFO -- : worker=0 ready
```

Restarting the service did not help. Deleting the dynamic directories out of /opt/geminabox/data would temporarily cause the errors to stop, but they would return after 5 to 10 minutes. strace did not show anything obvious. I rebuilt the VM from scratch and immediately ran into the same issue. I was finally able to resolve the problem by rolling back to geminabox 0.13.1, so it appears to be an issue with the gem itself. I'm using rbenv to install the gems under ruby 1.9.3-p551. Here's a complete list of the installed gems:

```

#> /opt/rbenv//versions/1.9.3-p551/bin/gem list

*** LOCAL GEMS ***

bigdecimal (1.1.0)
builder (3.2.2)
faraday (0.9.2)
geminabox (0.13.3)
httpclient (2.7.1)
io-console (0.3)
json (1.5.5)
kgio (2.10.0)
minitest (2.5.1)
multipart-post (2.0.0)
nesty (1.0.2)
rack (1.6.4)
rack-protection (1.5.3)
raindrops (0.16.0)
rake (0.9.2.2)
rdoc (3.9.5)
sinatra (1.4.7)
tilt (2.0.2)
unicorn (5.1.0)
```

I'm not sure if it's relevant, but I did notice the following errors in strace when 0.13.3 was misbehaving:

```
clone(child_stack=0x7f918cbb4ff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f918cbb59d0, tls=0x7f918cbb5700, child_tidptr=0x7f918cbb59d0) = 31381
read(6, "k\247\272s\327\"\r+\253\326dP\311*\32\333\324h\316\257\261E\231\235\216\255N\240p8\205\243"..., 7605) = 7605
clock_gettime(CLOCK_MONOTONIC, {2431, 507269670}) = 0
futex(0xf836a4, FUTEX_WAIT_PRIVATE, 12973, NULL) = 0
futex(0xf83708, FUTEX_WAKE_PRIVATE, 1)  = 0
open("/opt/rbenv/rbenv.d/exec/gem-rehash/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/rbenv.d/exec/gem-rehash/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/stringio.so", O_RDONLY) = 10
fstat(10, {st_mode=S_IFREG|0755, st_size=86205, ...}) = 0
fstat(10, {st_mode=S_IFREG|0755, st_size=86205, ...}) = 0
close(10)                               = 0
open("/opt/rbenv/rbenv.d/exec/gem-rehash/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/rbenv.d/exec/gem-rehash/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/zlib.so", O_RDONLY) = 10
fstat(10, {st_mode=S_IFREG|0755, st_size=200061, ...}) = 0
fstat(10, {st_mode=S_IFREG|0755, st_size=200061, ...}) = 0
close(10)                               = 0
close(9)                                = 0
unlink("/tmp/geminabox20161018-24282-mid4z3") = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT KILL USR1 SEGV USR2 TERM CHLD STOP TTIN TTOU VTALRM WINCH RTMIN RT_1], NULL, 8) = 0
open("/opt/rbenv/rbenv.d/exec/gem-rehash/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/stringio.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/rbenv.d/exec/gem-rehash/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/stringio.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/stringio.so", O_RDONLY) = 9
fstat(9, {st_mode=S_IFREG|0755, st_size=86205, ...}) = 0
fstat(9, {st_mode=S_IFREG|0755, st_size=86205, ...}) = 0
close(9)                                = 0
open("/opt/rbenv/rbenv.d/exec/gem-rehash/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/zlib.rb", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/rbenv.d/exec/gem-rehash/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/kgio-2.10.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/raindrops-0.17.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/unicorn-5.1.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.6.4/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/tilt-2.0.5/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/sinatra-1.4.7/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/builder-3.2.2/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/httpclient-2.8.2.4/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/nesty-1.0.2/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/multipart-post-2.0.0/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/faraday-0.9.2/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/geminabox-0.13.3/lib/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/1.9.1/x86_64-linux/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/site_ruby/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/1.9.1/x86_64-linux/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/vendor_ruby/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/zlib.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/x86_64-linux/zlib.so", O_RDONLY) = 9
fstat(9, {st_mode=S_IFREG|0755, st_size=200061, ...}) = 0
fstat(9, {st_mode=S_IFREG|0755, st_size=200061, ...}) = 0
close(9)                                = 0


```

**Comment by sonots** [comment]
What I merged from 0.13.1 are

* https://github.com/geminabox/geminabox/pull/244
* https://github.com/geminabox/geminabox/pull/245
* https://github.com/geminabox/geminabox/pull/247

But, it looks they work fine on my environment...

**Comment by sonots** [comment]
We dropped the support of ruby 1.9.3, but it looks you are using 1.9.3. Is it the cause?

**Comment by sonots** [comment]
BTW, your strace shows it finally detected stringio.so, and zlib.so. So, it should be fine.

**Comment by sonots** [comment]
This problem would be related with https://github.com/geminabox/geminabox/issues/217, and 0.13.3 might not be a cause. It takes long time to detect zlib.so?

**Comment by oberones** [comment]
Thank you for your help, sonots! I believe you are correct about [#217](https://github.com/geminabox/geminabox/issues/217). Even after rolling back to 0.13.1, our geminabox servers are still crashing with the same errors about the worker process. It seems to have taken a few hours after the roll back for the errors to come back. Unfortunately, the system is unable to recover once the errors begin and restarting the service does not bring it back for any meaningful amount of time. I will create a new VM with an updated version of Ruby and see if that helps. Do you know of any other workaround for [#217](https://github.com/geminabox/geminabox/issues/217)?

**Comment by sonots** [comment]
I could not reproduce #217, so I do not know any workarounds for it.
If you find how to reproduce, please let me know.

**Comment by oberones** [comment]
I'm not sure how to reproduce it in your environment, but it's happening with each new VM that I create. But it doesn't happen until the VM is under production load. If I stand up a new VM and then create a script that installs 5 or 6 gems over and over in a loop, it won't reproduce the issue. But if I change the production VIP to the new VM, the worker threads will start timing out within an hour or two. I forgot to mention that when this problem occurs, the latest_specs.4.8.gz and specs.4.8.gz in the proxy folder become 0 byte files:

```
drwxr-xr-x. 3 root root 4.0K Oct 18 22:27 .
drwx------. 7 root root 4.0K Oct 18 22:16 ..
-rw-r--r--. 1 root root    0 Oct 19 13:55 latest_specs.4.8.gz
-rw-r--r--. 1 root root 186K Oct 19 10:53 prerelease_specs.4.8.gz
drwxr-xr-x. 3 root root 4.0K Oct 18 20:58 quick
-rw-r--r--. 1 root root    0 Oct 19 12:58 specs.4.8.gz
```

**Comment by oberones** [comment]
In case it helps anyone, here's the the final output from strace before the master kills the worker:

```
gettimeofday({1476888357, 716650}, NULL) = 0
brk(0x5fb5000)                          = 0x5fb5000
write(6, "\37\213\10\0%\207\7X\0\3\214\275k\250-\351\225\30\226{\272\325}\373\276_\347\334\367\263_\222"..., 1060857) = 1060857
close(6)                                = 0
stat("/opt/geminabox/data/proxy/latest_specs.4.8.gz", {st_mode=S_IFREG|0644, st_size=1060857, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/opt/geminabox/data/proxy/latest_specs.4.8.gz", {st_mode=S_IFREG|0644, st_size=1060857, ...}) = 0
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT KILL USR1 SEGV USR2 TERM CHLD STOP TTIN TTOU VTALRM WINCH RTMIN RT_1], NULL, 8) = 0
gettimeofday({1476888357, 915595}, NULL) = 0
write(5, "HTTP/1.1 200 OK\r\nDate: Wed, 19 O"..., 213) = 213
open("/opt/geminabox/data/proxy/latest_specs.4.8.gz", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=1060857, ...}) = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=1060857, ...}) = 0
ioctl(6, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffee0b7a6f0) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(6, 0, SEEK_SET)                   = 0
read(6, "\37\213\10\0%\207\7X\0\3\214\275k\250-\351\225\30\226{\272\325}\373\276_\347\334\367\263_\222"..., 8192) = 8192
write(5, "\37\213\10\0%\207\7X\0\3\214\275k\250-\351\225\30\226{\272\325}\373\276_\347\334\367\263_\222"..., 8192) = 8192
read(6, "\367P\223\247\337%\321\241\366\374\270!\346<i\16\254yNq\304w\4\32:T\340\3\266\314\375c"..., 8192) = 8192
write(5, "\367P\223\247\337%\321\241\366\374\270!\346<i\16\254yNq\304w\4\32:T\340\3\266\314\375c"..., 8192) = 8192
read(6, "\363A\346\21U\1y\253\371\354\273\32\305e@\360O\253N\236\34\205\310\1\253-\225\365.\333W\370"..., 8192) = 8192
write(5, "\363A\346\21U\1y\253\371\354\273\32\305e@\360O\253N\236\34\205\310\1\253-\225\365.\333W\370"..., 8192) = 8192
read(6, "i\221\200?\260\22t\303. e}\240U\203\211\307\364\353\177}\331M\345)\242>|\20=5A"..., 8192) = 8192
write(5, "i\221\200?\260\22t\303. e}\240U\203\211\307\364\353\177}\331M\345)\242>|\20=5A"..., 8192) = 8192
read(6, "Eo_\323\245\16\351\251T\33\352&\345\207\356\350R\203\26\35%Er\211\371\242\254\37\256\335\242\367"..., 8192) = 8192
write(5, "Eo_\323\245\16\351\251T\33\352&\345\207\356\350R\203\26\35%Er\211\371\242\254\37\256\335\242\367"..., 8192) = 8192
read(6, "\312\3551\34\367Y\214f\226\367\0\331\261\215\235\212\37u\342\273\343\337\241\326\232\334\340\357\261\6\231?"..., 8192) = 8192
write(5, "\312\3551\34\367Y\214f\226\367\0\331\261\215\235\212\37u\342\273\343\337\241\326\232\334\340\357\261\6\231?"..., 8192) = 8192
read(6, ":\310\206xc\237\366\223\360 \273\255\351\221\n\333j\"/\236\236\255c\333L\211\231\334\363\5`\261"..., 8192) = 8192
write(5, ":\310\206xc\237\366\223\360 \273\255\351\221\n\333j\"/\236\236\255c\333L\211\231\334\363\5`\261"..., 8192) = 8192
read(6, "U\325\317\274C]\2518\313\213T\354\365\232\16D\20\235\313\356\371\303mk\305\5\203\243\262\347\370\16"..., 8192) = 8192
write(5, "U\325\317\274C]\2518\313\213T\354\365\232\16D\20\235\313\356\371\303mk\305\5\203\243\262\347\370\16"..., 8192) = 8192
read(6, "\242\17d|K\256+\373P\361L\231#c\342)\223\"\3569C\357\6;v\226\360\242\275/{e"..., 8192) = 8192
write(5, "\242\17d|K\256+\373P\361L\231#c\342)\223\"\3569C\357\6;v\226\360\242\275/{e"..., 8192) = 8192
read(6, "8z7\247\313,\24\34\221$\222\5\vD\0077\234E2e\217\302\341G\303o\210O&\352\356>"..., 8192) = 8192
write(5, "8z7\247\313,\24\34\221$\222\5\vD\0077\234E2e\217\302\341G\303o\210O&\352\356>"..., 8192 <unfinished ...>
+++ killed by SIGKILL +++
```

**Comment by sonots** [comment]
It looks it is working (writing), but unicorn forcedly killed the worker because of timeout.
The reason would be just because the disk is slow.

BTW, strace's -tt option shows the time togher, so gives information how long it takes for writing.

**Comment by oberones** [comment]
I was finally able to work around this issue by provisioning three gem-in-a-box servers and load balancing them behind an nginx reverse proxy. I believe the root cause of the issue was latency between our internal network and the external ruby-gems (60+ seconds to get a response from rubygems.org). Unfortunately, gem-in-a-box does not seem to have been able to handle this situation gracefully and continuously crashed in a way that corrupted the local data files.
